version: 2.1

orbs:
  ssh-deployment: singularitynet/ssh-deployment@2.4.1

jobs:
  causality-detection:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          mainnet-port: "7012"
          testnet-port: "6310"
          run-command: "python3 run_service.py --ssl"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "Dockerfile"
          docker-no-cache: true
          docker-image: "causality_detection"
          docker-container: "CAUSALITY_DETECTION"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CAUSALITY_DETECTION}
  testing:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
        - ssh-deployment/test:
              ssh-host: ${SSH_HOST}
              ssh-user: ${SSH_USER}
              test-command: "sleep 20;python3 test_service.py"
              docker-container: "CAUSALITY_DETECTION"

workflows:
  build_deploy:
    jobs:
      - causality-detection
      - testing:
            requires:
                - causality-detection
